### ISSUE TITLE
Switching tab re-mounts the component within RN 0.24

### ISSUE THREAD

**Issue by aksonov** [ericvicenti/navigation-rfc#69] opened 2016-04-19 10:51 UTC
Again, it worked well within RN 0.22, any changes within navigationState internal structure?
https://github.com/aksonov/react-native-router-flux/issues/549

**Comment by jmurzy** [comment] 2016-04-20 03:58
This is likely a dupe of #61. 🤔

<b>Update</b>—

I believe @hedgerwang is working on this. Does this fix your issue? [facebook/react-native#81c62c5f](https://github.com/facebook/react-native/commit/81c62c5f41da2e34f0c0e19ca38843918c23c32b)

**Comment by ptomasroos** [comment] 2016-06-08 08:02
We're facing this problems as well.
How would one go about keeping certain scene's / routes always mounted on a tabbar for instance between tab switching @hedgerwang @ericvicenti ? Very well known behaviour which was supported in Navigator.

**Comment by jmurzy** [comment] 2016-06-08 09:09
@ptomasroos Are you losing component state when you set `index` to a different `route`? [Here](https://github.com/jmurzy/react-router-native/blob/master/modules/ReducerUtils.js#L119-L189)'s a sample implementation of a tabs reducer that keeps components mounted across tab switches. There's also a [sample app](https://github.com/jmurzy/react-router-native/tree/master/examples/Aviato) in the repo if you want to see it in action. 

If you can tell me how to reproduce the issue you're having, I might be able to help.

🍺

**Comment by grabbou** [comment] 2016-06-08 09:11
I think it's more the issue that `render()` method of the Navigator (in official UIExplorer examples) uses plain View and just `{this.renderTab}` kind of thing, which will unmount the component on tab change anyway.

I've been successfully using `react-native-tab-navigator` to handle tabs instead and that's been working well.

**Comment by ptomasroos** [comment] 2016-06-08 09:19
@jmurzy images gets removed and causes redownloading of images on switching tabs. Very noticeable. Instead vs being on a stack and going back one scene where the underlying Card is displayed already rendered.

Another thing how this is noticed is that scroll position of a list view is 'forgotten' between switching tabs because its unmounted. Hence I would like to avoid the unmounting :)

**Comment by jmurzy** [comment] 2016-06-08 09:30
That is correct. `Transitioner` and `AnimatedView` (deprecated) use style interpolators to animate a scene in and out. Your components that are off-screen are not unmounted unless you explicitly remove the `route` that renders that particular `scene` from `navigationState`.

@hedgerwang killed the old examples in UIExplorer. [Here](https://github.com/facebook/react-native/commit/1dc33b5f23640a60682ac879b9a3e94a4aa519d9)'s a newer example he recently pushed that uses `NavigationCardStack`.

@ptomasroos What React Native version are you using? NavigationExperimental is a moving target and I recommend you upgrade to **v0.28.0-rc.0** and see if that helps. You should not be losing component state i.e scroll position. These issues were addressed in #61.

🍺

**Comment by ptomasroos** [comment] 2016-06-08 12:21
Thanks for your efforts for explaining and responding! I will upgrade!

**Comment by ptomasroos** [comment] 2016-06-08 18:28
@hedgerwang created a great example how to keep Scene's mounted with tab bar items today.
https://github.com/facebook/react-native/commit/1dc33b5f23640a60682ac879b9a3e94a4aa519d9#diff-4447daf3edd577198f620da6f8ac5cc0R256

For me this can be closed.

**Closed as completed** 2016-06-08 19:04 UTC
